empleados/aplicaciones/home/urls.py
from django.urls import path
from .views import *

app_name= 'prueba'

urlpatterns = [
    path('prueba/',IndexView.as_view(),name="correcto"),
    path('Lista/',PruebaListView.as_view()),
    path('prueba-create/',PruebaCreateView.as_view()),
    path('foundation-list/',Foundation.as_view()),

]

empleados/aplicaciones/persona/urls.py
from django.urls import path
from .views import *
from django.conf import  settings
from django.conf.urls.static import static
app_name  = "persona"

urlpatterns = [


    path('buscar-empleado/',ListarEmpleadosByKword.as_view()),
    path('listar-habilidades/',ListHabilidades.as_view()),
    path('success/',SuccessView.as_view(),name='correcto'),
    path('eliminar-empleado/<int:pk>/',EliminarEmpleado.as_view(),name='delete'),
    #####################URLS PRIMER PROYECTO############
    path('',InicioView.as_view(),name="home"),
    path('listar-empleados/',ListAllEmpleados.as_view(),name='list_empleados'),
    path('ver-empleado/<int:pk>/', EmpleadoDetail.as_view(),name='empleado_detail'),
    path('area-empleado/<str:area>/', ListByAreaEmpleado.as_view(),name='area_empleado'),
    path('administrar-empleado/', ListAdministrarEmpleado.as_view(),name='administrar_empleado'),
    path('update-empleado/<int:pk>/', UpdateEmpleado.as_view(), name='update'),
    path('create-empleados/', EmpleadoCreateView.as_view(),name='create'),

#############################URLS MULTIMEDIA #######################
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # LA puedo ver desde el servidor

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.home.urls')),
    path('', include('aplicaciones.persona.urls')),
    path('', include('aplicaciones.departamento.urls')),


]

empleados/aplicaciones/home/models.py
from django.db import models

class Prueba(models.Model):
    titulo = models.CharField(max_length=100)
    subtitulo = models.CharField(max_length=50)
    cantidad = models.IntegerField()


    def __str__(self):
        return  self.titulo

empleados/aplicaciones/persona/models.py
from django.db import models
from aplicaciones.departamento.models import Departamento
from ckeditor.fields import RichTextField
# Create your models here.

class Habilidades(models.Model):
    habilidades = models.CharField('Habilidad',max_length=50)


    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural= 'Habilidades'

    def __str__(self):
        return self.habilidades


class Empleado(models.Model):
    JOB_CHOICES = (
        ('0','contador'),
        ('1','administrador'),
        ('2','economista')
    )
    first_name = models.CharField('Nombres',max_length=60)
    last_name = models.CharField('Apellidos',max_length=60)
    full_name = models.CharField('Nombre completo',max_length=120,blank=True)
    job = models.CharField('Trabajos',max_length=1,choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento,on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='upload',blank=True,null=True)
    habilidades = models.ManyToManyField(Habilidades)
    #hoja_vida = RichTextField() #hace parte del plugin ckeditor
    def __str__(self):
        return self.first_name

    class Meta:
        verbose_name = 'Persona'
        verbose_name_plural= 'Personas'

empleados/aplicaciones/home/forms.py
from django import forms
from .models import *

class PruebaForm(forms.ModelForm):
    class Meta:
        model = Prueba
        fields = (
            'titulo',
            'subtitulo',
            'cantidad',
        )

        widgets = {
            'titulo': forms.TextInput(
                attrs= {
                    'placeholder': 'Ingrese un titulo',
                }
            )
        }

        #validaciones dentro del formulario
    def clean_cantidad(self):
        cantidad = self.cleaned_data['cantidad']
        if cantidad < 10:
            raise forms.ValidationError('Ingrese un numero mayor a 10')

        return cantidad

empleados/aplicaciones/persona/forms.py
from django.forms import *
from .models import *

class EmpleadoForm(ModelForm):
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',

        )

        widgets = {
            'habilidades': CheckboxSelectMultiple()

        }

empleados/aplicaciones/home/views.py
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView,ListView,CreateView

from aplicaciones.home.models import Prueba
from .forms import PruebaForm

class IndexView(TemplateView):
    template_name = 'success.html'

class PruebaListView(ListView):
    template_name = 'list.html'
    model = Prueba
    context_object_name = 'Lista'

class PruebaCreateView(CreateView):
    template_name = "add.html"
    model = Prueba
    form_class = PruebaForm
    success_url = reverse_lazy('prueba:correcto')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

class Foundation(TemplateView):
    template_name = "foundation.html"

empleados/aplicaciones/persona/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
# Create your views here.
from aplicaciones.persona.models import Empleado
from django.urls import reverse_lazy
from .forms import *


class ListarEmpleadosByKword(ListView):
    ''' Listar empleado por palabra clave'''
    template_name = 'clave.html'
    context_object_name = 'empleados'



    def get_queryset(self):
        palabra = self.request.GET.get("texto",'')#obtengo parametro por metodo GET
        list = Empleado.objects.filter(first_name__icontains=palabra)
        print('RESULTADO',list)
        return  []
#Relacion muchos a muchas
class ListHabilidades(ListView):
    template_name = 'habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(pk=6)#me recupera un unico rehistro
        return empleado.habilidades.all() #me trae todos las habilidades del empleado
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Lista Habilidades'
        return context

#DetailVIew

#CCreateView
class SuccessView(TemplateView):
    template_name = "success.html"

class PruebaCreate(CreateView):
    template_name = "create.html"
    model = Empleado
    fields = ['first_name','last_name','job','departamento','habilidades','hoja_vida']#trae todos los campos del modelo
    success_url = reverse_lazy('persona:correcto')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form): #interceptamos el formulario que se esta enviando para hacer el campo fullname
        empleado = form.save(commit=False) #almacenetodo lo que se ha obtenido en la base de datos el commite es para no hacer doble guardado
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save() # me actualiza el atributo al objeto
        return super(PruebaCreate, self).form_valid(form)

## INICIO DEL PRIMER PROYECTO ##
class InicioView(TemplateView):
    template_name = "home.html"

class ListAllEmpleados(ListView):
    template_name = 'list_all.html'
    paginate_by = 6 #para la paginacion de los resultados el crea un objeto de paginacion
    context_object_name = 'consulta'
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
        palabra = self.request.GET.get("kword",'')#obtengo parametro por metodo GET
        print('palabra :', palabra)
        list = Empleado.objects.filter(first_name__icontains=palabra)
        return  list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lista Empleados'
        context['place_holder'] = 'Buscar empleado'
        return context


    #traer empleados por departamento
    # queryset = Empleado.objects.filter(
    #     departamento__name= 'contabilidad'
    # )

    #sobrescribimos el query set
    # pasamos parametro por url
    #def get_queryset(self):
    #    area = self.kwargs['shortname'] #para recoger lo que me llega por url
    #    lista = Empleado.objects.filter(
    #        departamento__name__icontains =  area
    #    )
    #    return lista

class ListByAreaEmpleado(ListView):
    template_name = 'list_area.html'
    context_object_name = 'consulta'


    def get_queryset(self):
        area = self.kwargs['area']
        list = Empleado.objects.filter(departamento__name__contains=area)
        return list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lista Empleados Por Area'
        context['place_holder'] = 'Buscar empleado'
        return context

class ListAdministrarEmpleado(ListView):
    template_name = 'administrar.html'
    paginate_by = 6
    context_object_name = 'consulta'
    model = Empleado

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def get_queryset(self):
        palabra = self.request.GET.get("kword",'')#obtengo parametro por metodo GET
        print('palabra :', palabra)
        list = Empleado.objects.filter(first_name__icontains=palabra)
        return  list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lista Empleados'
        context['place_holder'] = 'Buscar empleado'
        return context

class UpdateEmpleado(UpdateView):
    template_name = "update.html"
    model = Empleado
    fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades']
    success_url = reverse_lazy('persona:administrar_empleado')
    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object() #recuperamos el objeto

        return super().post(request, *args, **kwargs)

    def form_valid(self, form): #interceptamos el formulario que se esta enviando para hacer el campo fullname
        empleado = form.save(commit=False) #almacenetodo lo que se ha obtenido en la base de datos el commite es para no hacer doble guardado
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save() # me actualiza el atributo al objeto
        return super(UpdateEmpleado, self).form_valid(form)

class EliminarEmpleado(DeleteView):
    model = Empleado
    template_name = "delete.html"
    success_url = reverse_lazy('persona:administrar_empleado')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

class EmpleadoCreateView(CreateView):
    template_name = "create.html"
    model = Empleado
    form_class = EmpleadoForm #trae todos los campos del modelo
    success_url = reverse_lazy('persona:list_empleados')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form): #interceptamos el formulario que se esta enviando para hacer el campo fullname
        empleado = form.save(commit=False) #almacenetodo lo que se ha obtenido en la base de datos el commite es para no hacer doble guardado
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save() # me actualiza el atributo al objeto
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoDetail(DetailView):
    model = Empleado
    template_name = "detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'empleado del mes'
        return context

empleados/aplicaciones/persona/templates/administrar.html
{% extends 'list.html' %}

{% block cabecera %}
      <th width="150">ID</th>
      <th width="150">Nombre</th>
      <th width="150">Apellidos</th>
      <th width="150">Departamento</th>
      <th width="150">Accion</th>
{% endblock %}

{% block cuerpo %}
    {% for e in consulta %}
    <tr>
      <td>{{ e.id }}</td>
      <td>{{ e.first_name}}</td>
      <td>{{ e.last_name}}</td>
      <td>{{ e.departamento}}</td>
        <td><a class="button warning" href="{% url 'persona:update' e.id %}">Editar</a></td>
        <td><a class="button alert" href="{% url 'persona:delete' e.id %}">eliminar</a></td>
    </tr>
    {% endfor %}

{% endblock %}

empleados/aplicaciones/persona/templates/clave.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form method="get">
        <input type="text" id="texto" name="texto" placeholder="ingrese nombre aqui">
        <button type="submit">Enviar</button>
    </form>

</body>
</html>

empleados/aplicaciones/persona/templates/create.html
{% extends 'base.html' %}
{% block title %}
    Crear Empleado
{% endblock %}

{% block contenido %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Registrar Empleado</h1>
                {% csrf_token %}
            <form class="grid-x grid-margin-x" method="post"  enctype="multipart/form-data">
                <div class=" cell large-6 cell">
                    <label>Nombres:
                      {{ form.first_name }}
                    </label>
                </div>
                <div class=" cell large-6 cell">
                    <label>Apellidos:
                      {{ form.last_name }}
                    </label>
                </div>
                 <div class=" cell large-6 cell">
                    <label>Trabajo:
                      {{ form.job }}
                    </label>
                </div>
                 <div class=" cell large-6 cell">
                    <label>Departamento:
                      {{ form.departamento }}
                    </label>
                </div>
                <div class=" cell large-6 cell">
                    <label>Habilidades:
                      {{ form.habilidades }}
                    </label>
                </div>
                <div class=" cell large-6 cell">
                    <label>Avatar:
                      {{ form.avatar }}
                    </label>
                </div>
                    <div class=" cell ">
                        <button type="submit" class="success button">Actualizar</button>
                    </div>
            </form>

        </div>
    </div>


{% endblock %}

empleados/aplicaciones/persona/templates/delete.html
{% extends 'base.html'  %}

{% block title %}
    Eliminar Empleado
{% endblock %}

{% block contenido %}

    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Eliminar Empleado: {{ object.first_name }}</h1>
             <form  class="cell" method="post">
                 <div class="callout alert">
                  <h5>Alerta</h5>
                  <p>¿Esta seguro de eliminar este empleado ?</p>
                </div>
                 <button type="submit" class="alert button">Eliminar</button>
             </form>
        </div>
    </div>
    {% csrf_token %}


{% endblock %}

empleados/aplicaciones/persona/templates/detail_empleado.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{ object.first_name }}
{% endblock %}
{% block contenido %}
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center" >
            <div class="cell large-4 card" style="width: 300px;">
              <div class="card-divider">
                <h4>{{ object.get_job_display }}</h4> <!-- para cuando tenemos con choices -->
              </div>
                {% if empleado.avatar %}
                    <img src="{{ object.avatar.url }}">
                {% else %}
                    <img src="{% static 'img/no_found.png' %}">
                {% endif %}
              <div class="card-section">
                  <h4>{{ empleado.full_name }}</h4>
                  <p><span class="label">Cargo</span></p>
                  <p>{{ empleado.departamento }}</p>
                  <p><span class="label">Habilidades</span></p>
                  <ul class="vertical menu">
                        {% for h in empleado.habilidades.all %}<!-- traigo el objeto con la lista de las habilidades-->
                            <li>{{ h }}</li>
                        {% endfor %}
                  </ul>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

empleados/aplicaciones/persona/templates/habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ titulo }}</title>
</head>
<body>
<h1>Habilidades</h1>
<ul>
    {% for h in habilidades %}
        <li>
            {{ h }}
        </li>
    {% endfor %}
</ul>

</body>
</html>

empleados/aplicaciones/persona/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Pagina de inicio
{% endblock %}



{% block contenido%}
    <!-- Acordeon -->
<div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
  <div class="orbit-wrapper">
    <div class="orbit-controls">
      <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
      <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
    </div>
    <ul class="orbit-container">
      <li class="is-active orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/ojo.jpg' %}" alt="Space">
          <figcaption class="orbit-caption">Space, the final frontier.</figcaption>
        </figure>
      </li>
      <li class="orbit-slide">
        <figure class="orbit-figure">
          <img class="orbit-image" src="{% static 'img/anime.jpg' %}" alt="Space">
          <figcaption class="orbit-caption">Lets Rocket!</figcaption>
        </figure>
      </li>
    </ul>
  </div>
  <nav class="orbit-bullets">
    <button class="is-active" data-slide="0">
      <span class="show-for-sr">First slide details.</span>
      <span class="show-for-sr" data-slide-active-label>Current Slide</span>
    </button>
    <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
  </nav>
</div>

    <!-- Bloque de Bienvenida -->
<div class="grid-x align-center">
    <h1 class="cell large-8" style="font-size:30px; text-align: center "> Bienvenido al sistema de registro de empleados</h1>
    <div class="cell large-7">
        <div class="callout">
          <p class style="text-align: center">Bienvenido al gestor de administrador de empeados NAMEINC   <a href="#" >Ver empleados</a></p>

        </div>
    </div>

</div>

    <!-- Fin Bloque bienvenida -->


<!-- fin acordeon -->
{% endblock %}

empleados/aplicaciones/persona/templates/list_all.html
{% extends 'list.html' %}

{% block cabecera %}
      <th width="150">ID</th>
      <th width="150">Nombre</th>
      <th width="150">Apellidos</th>
      <th width="150">Departamento</th>
      <th width="150">Accion</th>
{% endblock %}

{% block cuerpo %}
    {% for e in consulta %}
    <tr>
      <td>{{ e.id }}</td>
      <td>{{ e.first_name}}</td>
      <td>{{ e.last_name}}</td>
      <td>{{ e.departamento}}</td>
        <td><a class="button warning" href="{% url 'persona:empleado_detail' e.id %}">ver</a></td>
    </tr>
    {% endfor %}

{% endblock %}

empleados/aplicaciones/persona/templates/list_area.html
{% extends 'list.html' %}

{% block buscador %}

{% endblock %}

{% block cabecera %}
      <th width="150">ID</th>
      <th width="150">Nombre</th>
      <th width="150">Apellidos</th>
      <th width="150">Departamento</th>
{% endblock %}

{% block cuerpo %}
    {% for e in consulta %}
    <tr>
      <td>{{ e.id }}</td>
      <td>{{ e.first_name}}</td>
      <td>{{ e.last_name}}</td>
      <td>{{ e.departamento}}</td>
    </tr>
    {% endfor %}

{% endblock %}

empleados/aplicaciones/persona/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Holiii</h1>
</body>
</html>

empleados/aplicaciones/persona/templates/update.html
{% extends 'base.html' %}
{% block title %}
    Editar Empleado
{% endblock %}

{% block contenido %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Modificar empleado</h1>
            <div class="cell">
                <form class="grid-x grid-margin-x" method="post">
                    <div class=" cell large-6 cell">
                        <label>Nombres:
                          {{ form.first_name }}
                        </label>
                    </div>
                    <div class=" cell large-6 cell">
                        <label>Apellidos:
                          {{ form.last_name }}
                        </label>
                    </div>
                     <div class=" cell large-6 cell">
                        <label>Trabajo:
                          {{ form.job }}
                        </label>
                    </div>
                     <div class=" cell large-6 cell">
                        <label>Departamento:
                          {{ form.departamento }}
                        </label>
                    </div>
                    <div class=" cell large-6 cell">
                        <label>Habilidades:
                          {{ form.habilidades }}
                        </label>
                    </div>
                    <div class=" cell ">
                        <button type="submit" class="success button">Actualizar</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
    {% csrf_token %}

{% endblock %}