empleados/aplicaciones/departamento/urls.py
from django.urls import path
from .views import *

app_name = "departamento"

urlpatterns = [

   ##############################33 #Inicio Proyectoooo#################33
    path('list_departamento/',DepartamentoListView.as_view(),name="list_departamento"),
    path('new_departamento/', NewDepartamento.as_view(), name="new_departamento"),

]

empleados/aplicaciones/persona/urls.py
from django.urls import path
from .views import *
from django.conf import  settings
from django.conf.urls.static import static
app_name  = "persona"

urlpatterns = [


    path('buscar-empleado/',ListarEmpleadosByKword.as_view()),
    path('listar-habilidades/',ListHabilidades.as_view()),
    path('success/',SuccessView.as_view(),name='correcto'),
    path('eliminar-empleado/<int:pk>/',EliminarEmpleado.as_view(),name='delete'),
    #####################URLS PRIMER PROYECTO############
    path('',InicioView.as_view(),name="home"),
    path('listar-empleados/',ListAllEmpleados.as_view(),name='list_empleados'),
    path('ver-empleado/<int:pk>/', EmpleadoDetail.as_view(),name='empleado_detail'),
    path('area-empleado/<str:area>/', ListByAreaEmpleado.as_view(),name='area_empleado'),
    path('administrar-empleado/', ListAdministrarEmpleado.as_view(),name='administrar_empleado'),
    path('update-empleado/<int:pk>/', UpdateEmpleado.as_view(), name='update'),
    path('create-empleados/', EmpleadoCreateView.as_view(),name='create'),

#############################URLS MULTIMEDIA #######################
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # LA puedo ver desde el servidor

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.home.urls')),
    path('', include('aplicaciones.persona.urls')),
    path('', include('aplicaciones.departamento.urls')),


]

empleados/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% block navbar %}
    {% include 'header.html' %}
{% endblock %}

{% block contenido %}
{% endblock %}


    <script src="{% static 'js/vendor/jquery.js' %}"></script>
    <script src="{% static 'js/vendor/what-input.js' %}"></script>
    <script src="{% static 'js/vendor/foundation.min.js' %}"></script>
    <script>
        $(document).foundation();
    </script>
</body>
</html>

empleados/templates/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
        <li><a href="{% url 'persona:list_empleados' %}">Listar</a></li>
      <li><a href="{% url 'departamento:list_departamento' %}">Departamentos</a></li>
      <li><a href="{% url 'persona:administrar_empleado' %}">Administrar</a></li>
      <li><a href="{% url 'departamento:new_departamento' %}">Nuevo Departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado"></li>
      <li><a class="button" href="{% url 'persona:create' %}">Registrar Nuevo</a></li>
    </ul>
  </div>
</div>

empleados/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

empleados/templates/list.html
{% extends 'base.html' %}


{% block contenido %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">{{ title }}</h1>
            {% block buscador %}
            {% csrf_token %}
            <form  method="get" class="cell grid-x grid-margin-x" > <!-- se define una fila -->
                <div class="cell large-8 "> <!-- se crean las columnas -->
                    <input type="text" id="kword" name="kword" placeholder="{{ place_holder }}">
                </div>
                <div class="cell large-4"><!-- se crean las columnas -->
                    <button type="submit" class="success button">Buscar</button>
                </div>
            </form>
            {% endblock %}
            <div class="cell"> <!-- se crea la taba -->
                <table>
                  <thead>
                    <tr>
                        {% block cabecera %}
                         {% endblock %}
                    </tr>
                  </thead>
                  <tbody>
                      {% block cuerpo %}
                      
                      {% endblock %}
                  </tbody>
                </table>
            </div>
            <div class="cell">
                {% if is_paginated %}
                    <nav aria-label="Pagination">
                      <ul class="pagination">
                          {% if page_obj.has_previous %} <!-- si este objeto tiene paginas atras muestrame el previus -->
                                <li class="pagination-previous ">
                                    <a href="?page={{page_obj.previous_page_number  }}">Atras</a>
                                </li>
                          {% endif %}
                          {% for pagina in paginator.page_range %} <!-- traigo el numero de paginas del objeto de paginacion -->
                              {% ifequal pagina page_obj.number %} <!-- comparacion para marcar la pagina en la que estoy -->
                                   <li class="current"><span class="show-for-sr">You're on page</span>{{ pagina }}</li>
                                  {% else %}
                                      <li><a href="?page={{ pagina }}" aria-label="Page 2">{{ pagina }}</a></li>
                              {% endifequal %}

                          {% endfor %}


                        {% if page_obj.has_next %}
                        <li class="pagination-next">
                             <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                        </li>
                        {% endif %}
                      </ul>
                    </nav>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}