empleados/aplicaciones/departamento/urls.py
from django.urls import path
from .views import *

app_name = "departamento"

urlpatterns = [

   ##############################33 #Inicio Proyectoooo#################33
    path('list_departamento/',DepartamentoListView.as_view(),name="list_departamento"),
    path('new_departamento/', NewDepartamento.as_view(), name="new_departamento"),

]

empleados/aplicaciones/persona/urls.py
from django.urls import path
from .views import *
from django.conf import  settings
from django.conf.urls.static import static
app_name  = "persona"

urlpatterns = [


    path('buscar-empleado/',ListarEmpleadosByKword.as_view()),
    path('listar-habilidades/',ListHabilidades.as_view()),
    path('success/',SuccessView.as_view(),name='correcto'),
    path('eliminar-empleado/<int:pk>/',EliminarEmpleado.as_view(),name='delete'),
    #####################URLS PRIMER PROYECTO############
    path('',InicioView.as_view(),name="home"),
    path('listar-empleados/',ListAllEmpleados.as_view(),name='list_empleados'),
    path('ver-empleado/<int:pk>/', EmpleadoDetail.as_view(),name='empleado_detail'),
    path('area-empleado/<str:area>/', ListByAreaEmpleado.as_view(),name='area_empleado'),
    path('administrar-empleado/', ListAdministrarEmpleado.as_view(),name='administrar_empleado'),
    path('update-empleado/<int:pk>/', UpdateEmpleado.as_view(), name='update'),
    path('create-empleados/', EmpleadoCreateView.as_view(),name='create'),

#############################URLS MULTIMEDIA #######################
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # LA puedo ver desde el servidor

empleados/empleados/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplicaciones.home.urls')),
    path('', include('aplicaciones.persona.urls')),
    path('', include('aplicaciones.departamento.urls')),


]

empleados/aplicaciones/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre',max_length=50)#el nombre es como aparecera en el administrador de django
    short_name = models.CharField('Nombre Corto', max_length=50,blank=True)
    anulate = models.BooleanField('Anulado',default=False)

    class Meta:
        verbose_name= 'Mi departamento'
        verbose_name_plural = 'Mis departamentos'
        ordering = ['name']
        #unique_together = ('name','shor_name') #no permite que se registre un atributo dos veces

    def __str__(self):
        return self.name

empleados/aplicaciones/departamento/forms.py
from django import forms

class NewDepartamento(forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    shorname = forms.CharField(max_length=50)

empleados/aplicaciones/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.edit import FormView
from django.views.generic import ListView, DetailView, CreateView, TemplateView, UpdateView, DeleteView
from .forms import *
from aplicaciones.persona.models import *
from .models import *
# Create your views here.
class NewDepartamento(FormView): #Esta vista no trabja directamente con modelos
    template_name = "departamento.html"
    form_class = NewDepartamento
    success_url = reverse_lazy('departamento:list_departamento')

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


    def form_valid(self, form):
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        depa = Departamento.objects.create(
            name= form.cleaned_data['departamento'],
            short_name= form.cleaned_data['shorname']
        )
        Empleado.objects.create( #crar registro
            first_name= nombre,
            last_name= apellido,
            job = '1',
            departamento= depa
        )
        return  super(NewDepartamento, self).form_valid(form)

class DepartamentoListView(ListView):
    template_name = 'departamento_list.html'
    model = Departamento
    context_object_name = 'consulta'
    paginate_by = 2  # para la paginacion de los resultados el crea un objeto de paginacion
    ordering = 'id'
   # def get_queryset(self):
   #     palabra = self.request.GET.get("kword", '')  # obtengo parametro por metodo GET
   #     list = Departamento.objects.filter(name__icontains=palabra)
   #     return list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lista Departamentos'
        context['place_holder'] = 'Buscar Departamento'
        return context

empleados/aplicaciones/departamento/templates/departamento.html
{% extends 'base.html' %}
{% block title %}
    Nuevo Departamento
{% endblock %}
{% block contenido %}
    <div class="grid-container">
        <div class="grid-x">
             <h1 class="cell">Registrar Nuevo departamento</h1>
                {% csrf_token %}
             <form class=" cell callout grid-x grid-margin-x" method="post"  enctype="multipart/form-data">
                 <h3 class="cell large-12"> Datos Empleado</h3>
                 <div class=" cell large-6 cell">
                    <label>Nombre:
                      {{ form.nombre }}
                    </label>
                </div>
                 <div class=" cell large-6 cell">
                    <label>Apellidos:
                    {{ form.apellidos }}
                    </label>
                </div>
                 <h3 class="cell large-12"> Datos Departamento</h3>
                 <div class=" cell large-6 cell">
                    <label>Departamento:
                    {{ form.departamento }}
                    </label>
                </div>
                 <div class=" cell large-6 cell">
                    <label>Alias:
                    {{ form.shorname }}
                    </label>
                </div>
                 <div class=" cell ">
                     <button type="submit" class="success button">Actualizar</button>
                 </div>
             </form>
        </div>
    </div>
{% endblock %}


</body>
</html>

empleados/aplicaciones/departamento/templates/departamento_list.html
{% extends 'list.html' %}

{% block buscador %}

{% endblock %}

{% block cabecera %}
    <th width="150">ID</th>
    <th width="150">Departamento</th>
    <th width="150">Accion</th>

{% endblock %}

{% block cuerpo %}
    {% for d in consulta %}
    <tr>
        <td>{{ d.id }}</td>
        <td>{{ d.name }}</td>
       <td><a class="button warning" href="{% url 'persona:area_empleado' d.name %}">ver</a></td>
    </tr>
    {% endfor %}
{% endblock %}